project_name: bundle-inspector

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: bundle-inspector
    main: ./cmd/bundle-inspector
    binary: bundle-inspector
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: bundle-inspector
    format: tar.gz
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    files:
      - README.md
      - LICENSE*
      - bitrise-plugin.yml

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - 'typo'

release:
  github:
    owner: bitrise-io
    name: bitrise-plugins-bundle-inspector
  draft: false
  prerelease: auto
