name: bundle-inspector
description: |
  Analyze iOS and Android app bundles to understand size composition,
  identify optimization opportunities, and track size trends over time.

  Features:
  - iOS: .ipa, .app bundle analysis
  - Android: .apk, .aab analysis
  - Duplicate file detection
  - Image optimization recommendations
  - Loose image detection
  - Unnecessary file detection
  - JSON and text report export to deploy directory
  - Auto-detects bundle paths from Bitrise environment variables

executable:
  osx: https://github.com/bitrise-io/bitrise-plugins-bundle-inspector/releases/download/0.2.1/bundle-inspector-Darwin-x86_64
  osx-arm64: https://github.com/bitrise-io/bitrise-plugins-bundle-inspector/releases/download/0.2.1/bundle-inspector-Darwin-arm64
  linux: https://github.com/bitrise-io/bitrise-plugins-bundle-inspector/releases/download/0.2.1/bundle-inspector-Linux-x86_64

trigger: ""

requirements:
  - tool: bitrise
    min_version: 1.3.0
    max_version: ""
